yandex_smart_home:
  filter:
    include_entity_globs:
      - sensor.a4c1381840a0_temperature # livingroom
      - sensor.a4c138041e22_temperature # bedroom
      - sensor.a4c138a0dbd3_temperature # childrenroom
      - sensor.a4c138aed13a_temperature # kitchen
      - sensor.a4c138b90c73_temperature # balcony
      - binary_sensor.smartintercom_state # домофон
      - binary_sensor.0x00158d0002890189_contact
      - sensor.0x00158d000246651d_action
      - light.clock_light
      - light.hallway_light
      - media_player.televizor_v_gostinoi
      - sensor.mh_z19_co2_value
      - sensor.mh_z19_co2_value_2
      - humidifier.uvlazhnitel
      - humidifier.uvlazhnitel_2
      - humidifier.smartmi_evaporative_humidifier
      - light.neopixel_light
      - button.garland_power
      - button.garland_power_2
  color_profile:
    profile_clock:
      red: ["255", "0", "0"]
      green: ["0", "255", "0"]
      blue: ["0", "0", "255"]
  entity_config:
    button.garland_power:
      name: Елочка
      room: Гостиная
      custom_toggles:
        backlight:
          turn_on:
            service: button.press
            entity_id: button.garland_effect
          turn_off:
            service: button.press
            entity_id: button.garland_effect
    button.garland_power_2:
      name: Гирлянда
      room: Спальня
      custom_toggles:
        backlight:
          turn_on:
            service: button.press
            entity_id: button.garland_effect_2
          turn_off:
            service: button.press
            entity_id: button.garland_effect_2
    humidifier.uvlazhnitel:
      name: Увлажнитель
      room: Гостиная
      properties:
        - type: water_level
          entity: sensor.uvlazhnitel_water_level
    humidifier.uvlazhnitel_2:
      name: Увлажнитель
      room: Детская
    humidifier.smartmi_evaporative_humidifier:
      name: Увлажнитель
      room: Спальня
      properties:
        - type: water_level
          entity: sensor.smartmi_evaporative_humidifier_water_level
    sensor.mh_z19_co2_value:
      name: Качество воздуха спальня
      room: Спальня
      properties:
        - type: co2_level
          entity: sensor.mh_z19_co2_value
        - type: pm2.5_density
          entity: sensor.concentration2_2_5um
        - type: pm1_density
          entity: sensor.concentration1_1_0um
        - type: pm10_density
          entity: sensor.concentration3_10um
    sensor.mh_z19_co2_value_2:
      name: Качество воздуха гостиная
      room: Гостиная
      properties:
        - type: co2_level
          entity: sensor.mh_z19_co2_value_2
        - type: pm2.5_density
          entity: sensor.concentration2_2_5um_2
        - type: pm1_density
          entity: sensor.concentration1_1_0um_2
        - type: pm10_density
          entity: sensor.concentration3_10um_2
    sensor.a4c1381840a0_temperature:
      name: Датчик гостиной
      room: Гостиная
      properties:
        - type: temperature
          entity: sensor.a4c1381840a0_temperature
        - type: humidity
          entity: sensor.a4c1381840a0_humidity
        - type: battery_level
          entity: sensor.a4c1381840a0_battery
    sensor.a4c138041e22_temperature:
      name: Датчик спальни
      room: Спальня
      properties:
        - type: temperature
          entity: sensor.a4c138041e22_temperature
        - type: humidity
          entity: sensor.a4c138041e22_humidity
        - type: battery_level
          entity: sensor.a4c138041e22_battery
    sensor.a4c138a0dbd3_temperature:
      name: Датчик детской
      room: Детская
      properties:
        - type: temperature
          entity: sensor.a4c138a0dbd3_temperature
        - type: humidity
          entity: sensor.a4c138a0dbd3_humidity
        - type: battery_level
          entity: sensor.a4c138a0dbd3_battery
    sensor.a4c138aed13a_temperature:
      name: Датчик кухни
      room: Кухня
      properties:
        - type: temperature
          entity: sensor.a4c138aed13a_temperature
        - type: humidity
          entity: sensor.a4c138aed13a_humidity
        - type: battery_level
          entity: sensor.a4c138aed13a_battery
    sensor.a4c138b90c73_temperature:
      name: Датчик балкона
      room: Балкон
      properties:
        - type: temperature
          entity: sensor.a4c138b90c73_temperature
        - type: humidity
          entity: sensor.a4c138b90c73_humidity
        - type: battery_level
          entity: sensor.a4c138b90c73_battery
    binary_sensor.0x00158d0002890189_contact:
      name: Датчик входной двери
      room: Прихожая
      properties:
        - type: open
          entity: binary_sensor.0x00158d0002890189_contact
        - type: battery_level
          entity: sensor.0x00158d0002890189_battery
    sensor.0x00158d000246651d_action:
      device_class: button
      name: Кнопка беспроводная
      room: Спальня
      properties:
        # - type: button
        #   entity: sensor.0x00158d000246651d_action
        - type: battery_level
          entity: sensor.0x00158d000246651d_battery
    light.hallway_light:
      name: "Люстра"
      room: "Прихожая"
    light.clock_light:
      name: "Часы"
      room: "Гостиная"
      color_profile: profile_clock
    light.neopixel_light:
      name: "Ночник"
      room: "Гостиная"
    media_player.televizor_v_gostinoi:
      name: Телевизор
      room: Гостиная
